name: mirge_py_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - snakemake-minimal
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - bowtie
  - cutadapt
  - samtools
  - biopython
  - scikit-learn
  - reportlab
  - pip
  - pip:
      - miRge3
